const numbers = new Set()
numbers.add(1).add(2).add(3)
console.log(numbers.size)
console.log(numbers.has(2))
console.log(numbers.has(22))
numbers.delete(1)
console.log(numbers)
numbers.clear()
console.log(numbers)
